theme = "PaperMod"

title = "Gabriel S Passos"
baseURL = "https://gabrielpassos.com/"
languageCode = "en"

[params]
  author = "Gabriel S Passos"
  description = "Cybersecurity and Tech Blog"
  defaultTheme = "dark"   # dark | light | auto
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
    
[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 20
  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles/'
    weight = 30
  [[menus.main]]
    name = 'My Projects'
    pageRef = '/projects/'
    weight = 40
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact/'
    weight = 50

