theme = "PaperMod"

title = "Gabriel S Passos"
baseURL = "https://gabrielpassos.com/"
languageCode = "en"

[params]
  author = "Gabriel S Passos"
  description = "Cybersecurity blog about malware analysis, reverse engineering, security research and automation by Gabriel Passos"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
    
[params.assets]
  favicon = "icons/favicon.ico"
  favicon16x16 = "icons/favicon-16x16.png"
  favicon32x32 = "icons/favicon-32x32.png"
  apple_touch_icon = "icons/apple-touch-icon.png"
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 20
  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles/'
    weight = 30
  [[menus.main]]
    name = 'My Projects'
    pageRef = '/projects/'
    weight = 40

