theme = "PaperMod"

title = "My Blog"
baseURL = "https://gabrielpassos.com/"
languageCode = "en"

[params]
  author = "Gabriel S Passos"
  description = "Cybersecurity and Tech Blog"
  defaultTheme = "dark"   # dark | light | auto
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
